# Copyright © 2019 MizukiSonoko. All rights reserved.
version: 2.0
jobs:
  base:
    docker:
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/MizukiSonoko/habakari-honoka
    steps:
      - checkout

      - run:
          name: install deps
          command: |
            GO111MODULE=on go mod vendor

      - run:
          name: build
          command: |
            make build

      - run:
          name: honoka
          command: |
            make honoka

workflows:
  version: 2
  default:
    jobs:
      - base

